# Generated by Django 4.0.5 on 2022-06-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fraud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn', models.CharField(max_length=12)),
                ('fraud_description', models.CharField(max_length=5000)),
                ('still_ongoing', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernamme', models.EmailField(max_length=254)),
                ('msisdn', models.CharField(max_length=12)),
                ('query_date', models.DateTimeField(verbose_name='date queried')),
            ],
        ),
    ]
